# Trabalho de introdução aos sistemas inteligentes Yago Faria 65509
##  Como a educação reflete na pobreza das grandes regiôes e dos municípios do brasil

1. Importar base de dados
2. Visualizar e tratar
3. Analisar base de dados
3. Construir uma analise

## 1. Importando base de dados

In [1]:
#bibliotecas
import pandas as pd
from pandas_ods_reader import read_ods
import  matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

### Legenda

In [2]:
#Legendas
legenda = read_ods('Dados/Dicionário de variáveis.ods')
display(legenda)

,cod_num,"Código do município, definido pelo IBGE",unnamed.1,unnamed.3,unnamed.4
0,nom_mun,Nome do município,None,None,None
1,cod_regiao,Código da Grande Região,None,None,None
2,cod_uf,Código da Unidade da Federação,None,None,None
3,cod_local,Código da Unidade Espacial,None,None,None
4,qtd_dom,Número de domicílios,None,None,None
5,qtd_dom_pobres,Número de domicílios pobres,None,None,None
6,qtd_dom_vulneraveis,Número de domicílios vulneráveis,None,None,None
7,qtd_dom_pob_vul,Número de domicílios pobres ou vulneráveis,None,None,None
8,qtd_pes,Número de pessoas,None,None,None
9,qtd_pes_pobres,Númeo de pessoas pobres,None,None,None
10,qtd_pes_vulneraveis,Número de pessoas vulneráveis,None,None,None
11,qtd_pes_pob_vul,Número de pessoas pobres ou vulneráveis,None,None,None
12,qtd_0a11,Número de crianças de com idade de 0 a 11 anos,None,None,None
13,qtd_0a11_pobres,Número de crianças de 0 a 11 anos pobres,None,None,None
14,qtd_0a11_vulneraveis,Número de crianças de 0 a 11 anos vulneráveis,None,None,None
15,qtd_0a11_pob_vul,Número de crianças de 0 a 11 anos pobres ou vu...,None,None,None
16,incidencia,Incidência da pobreza,None,None,None
17,intensidade,Intensidade da pobreza,None,None,None
18,IPM,Índice de Pobreza Multidimensional,None,None,None
19,qtd_dom_E1,Número de domicílios privados no indicador E1,None,None,None
20,qtd_dom_E2,Número de domicílios privados no indicador E2,None,None,None
21,qtd_dom_E3,Número de domicílios privados no indicador E3,None,Ver arquivo Quadro de indicadores e dimensões,None
22,qtd_dom_S1,Número de domicílios privados no indicador S1,None,None,None
23,qtd_dom_S2,Número de domicílios privados no indicador S2,None,None,None
24,qtd_dom_S3,Número de domicílios privados no indicador S3,None,None,None
25,qtd_dom_S4,Número de domicílios privados no indicador S4,None,None,None
26,qtd_dom_T1,Número de domicílios privados no indicador T1,None,None,None
27,qtd_dom_T2,Número de domicílios privados no indicador T2,None,None,None
28,qtd_dom_T3,Número de domicílios privados no indicador T3,None,None,None
29,qtd_dom_P1,Número de domicílios privados no indicador P1,None,None,None
30,qtd_dom_P2,Número de domicílios privados no indicador P2,None,None,None
31,qtd_dom_P3,Número de domicílios privados no indicador P3,None,None,None
32,qtd_dom_P4,Número de domicílios privados no indicador P4,None,None,Os dados dos indicadores utilizados no cálculo...
33,contr_E1,Contribuição do indicador E1 na composição do IPM,None,None,None
34,contr_E2,Contribuição do indicador E2 na composição do IPM,None,None,None
35,contr_E3,Contribuição do indicador E3 na composição do IPM,None,None,None
36,contr_S1,Contribuição do indicador S1 na composição do IPM,None,None,None
37,contr_S2,Contribuição do indicador S2 na composição do IPM,None,None,None
38,contr_S3,Contribuição do indicador S3 na composição do IPM,None,None,None
39,contr_S4,Contribuição do indicador S4 na composição do IPM,None,None,None
40,contr_T1,Contribuição do indicador T1 na composição do IPM,None,None,None
41,contr_T2,Contribuição do indicador T2 na composição do IPM,None,None,None
42,contr_T3,Contribuição do indicador T3 na composição do IPM,None,None,None
43,contr_P1,Contribuição do indicador P1 na composição do IPM,None,None,None
44,contr_P2,Contribuição do indicador P2 na composição do IPM,None,None,None
45,contr_P3,Contribuição do indicador P3 na composição do IPM,None,None,None
46,contr_P4,Contribuição do indicador P4 na composição do IPM,None,None,None
47,None,None,Fonte,None,None
48,num_idhm,índice de Desenvolvimento Humano Municipal,Atlas Brasil,None,None
49,num_ivs,Índice de Vulnerabilidade Social,IPEA,None,None
50,num_ibeu,Índice de Bem Estar Urbano,Observatório das Metrópoles,None,None
51,num_renda,Renda média (R$),IBGE,None,None

### brasil inteiro

In [3]:
#Legendas
legendab = read_ods('Dados/Agragacoes/Brasil.ods')
display(legendab)

,cod_local,qtd_dom,qtd_dom_pobres,qtd_dom_vulneraveis,qtd_dom_pob_vul,qtd_pes,qtd_pes_pobres,qtd_pes_vulneraveis,qtd_pes_pob_vul,qtd_0a11,...,contr_S2,contr_S3,contr_S4,contr_T1,contr_T2,contr_T3,contr_P1,contr_P2,contr_P3,contr_P4
0,0.0,58051449.0,1.022931e+07,7.057125e+06,1.728644e+07,1.907558e+08,4.491829e+07,2.521263e+07,7.013091e+07,3.562944e+07,...,8.897348,12.371005,8.08082,1.633721,3.154642,12.144514,4.556546,6.548337,13.683215,4.525888

### Por grande regiao

In [4]:
#Legendas
grande_regiao = read_ods('Dados/Agragacoes/Grandes Regiões.ods')
display(grande_regiao)

,cod_local,qtd_dom,qtd_dom_pobres,qtd_dom_vulneraveis,qtd_dom_pob_vul,qtd_pes,qtd_pes_pobres,qtd_pes_vulneraveis,qtd_pes_pob_vul,qtd_0a11,...,contr_S2,contr_S3,contr_S4,contr_T1,contr_T2,contr_T3,contr_P1,contr_P2,contr_P3,contr_P4
0,1.0,4025533.0,1.802688e+06,7.283711e+05,2.531059e+06,1.586445e+07,8.535353e+06,2.594659e+06,1.113001e+07,3.909592e+06,...,9.585028,12.582945,6.954705,1.430517,2.650321,11.488212,9.225784,7.451840,12.506263,4.309695
1,2.0,15038520.0,4.573013e+06,2.701714e+06,7.274728e+06,5.308195e+07,2.055919e+07,9.421909e+06,2.998110e+07,1.095601e+07,...,8.235742,11.493418,9.183616,1.545383,3.188079,11.725756,2.581652,6.523388,14.563499,6.063642
2,3.0,25576854.0,1.927231e+06,1.933984e+06,3.861215e+06,8.036441e+07,8.295707e+06,7.544151e+06,1.583986e+07,1.348047e+07,...,9.688631,12.270684,7.369750,1.654577,4.214953,13.291060,1.138577,7.239068,13.628530,3.222171
3,4.0,9008655.0,1.204629e+06,1.038157e+06,2.242787e+06,2.738689e+07,4.605877e+06,3.424155e+06,8.030032e+06,4.599166e+06,...,8.783778,14.282571,7.287619,2.244992,2.131791,12.377456,10.290672,4.377583,12.080869,2.052065
4,5.0,4401887.0,7.217502e+05,6.548986e+05,1.376649e+06,1.405809e+07,2.922156e+06,2.227753e+06,5.149909e+06,2.684193e+06,...,9.468443,14.663764,7.142426,1.705128,3.254256,13.336628,4.037194,6.020087,13.990034,2.557511

### por uf

In [5]:
#Legendas
legendadf = read_ods('Dados/Agragacoes/UF.ods')
display(legendadf)

,cod_local,qtd_dom,qtd_dom_pobres,qtd_dom_vulneraveis,qtd_dom_pob_vul,qtd_pes,qtd_pes_pobres,qtd_pes_vulneraveis,qtd_pes_pob_vul,qtd_0a11,...,contr_S2,contr_S3,contr_S4,contr_T1,contr_T2,contr_T3,contr_P1,contr_P2,contr_P3,contr_P4
0,11.0,468316.0,2.168250e+05,90022.603300,3.068477e+05,1.562409e+06,8.236513e+05,2.792960e+05,1.102947e+06,3.288374e+05,...,12.476418,14.105728,7.409531,1.540247,1.855212,12.038578,11.222508,4.127666,12.424846,2.369107
1,12.0,193692.0,9.033518e+04,36129.036008,1.264642e+05,7.335590e+05,4.095719e+05,1.195192e+05,5.290911e+05,1.962117e+05,...,10.169620,11.391412,6.603180,1.298478,2.265125,10.704262,12.424271,7.366202,12.641681,4.335996
2,13.0,806974.0,3.147591e+05,127378.061140,4.421372e+05,3.483985e+06,1.720347e+06,5.183046e+05,2.238651e+06,9.224367e+05,...,8.229971,11.370635,6.642655,1.657924,2.866945,10.654164,10.218199,9.403430,11.645364,5.197722
3,14.0,117965.0,3.559331e+04,18871.350676,5.446466e+04,4.504790e+05,1.774572e+05,7.236118e+04,2.498184e+05,1.184620e+05,...,7.245198,11.810904,8.157249,1.951396,2.641880,10.279844,8.948164,9.478105,12.415780,5.724596
4,15.0,1877876.0,9.659110e+05,342439.594111,1.308351e+06,7.581051e+06,4.566283e+06,1.202565e+06,5.768848e+06,1.857416e+06,...,9.676425,12.743738,6.958179,1.332942,2.635433,11.611776,8.714555,7.384363,12.595330,4.376771
5,16.0,158453.0,6.597114e+04,33308.026192,9.927916e+04,6.695260e+05,3.448750e+05,1.263132e+05,4.711882e+05,1.754834e+05,...,8.075505,13.993434,3.178678,1.196355,4.371693,12.622828,10.085262,9.530184,11.814153,3.731140
6,17.0,402257.0,1.132935e+05,80222.410328,1.935159e+05,1.383445e+06,4.931675e+05,2.762996e+05,7.694670e+05,3.107447e+05,...,8.365407,12.214691,9.191963,1.500815,2.981137,12.200496,3.729371,6.744881,14.836772,4.633121
7,21.0,1661659.0,7.895992e+05,331383.127162,1.120982e+06,6.574789e+06,3.701273e+06,1.167374e+06,4.868647e+06,1.604156e+06,...,7.975730,11.245447,10.460087,1.328252,2.373707,10.805969,6.359279,6.968122,14.020170,6.169066
8,22.0,852506.0,3.383129e+05,190377.443964,5.286903e+05,3.118360e+06,1.483983e+06,6.511477e+05,2.135130e+06,6.402122e+05,...,8.123826,9.894545,10.625996,1.425707,2.650135,11.386828,3.307858,6.085328,14.794140,6.436277
9,23.0,2380173.0,7.177025e+05,447749.493656,1.165452e+06,8.452381e+06,3.196336e+06,1.577471e+06,4.773806e+06,1.670927e+06,...,8.137318,12.006261,9.145736,1.533033,2.800735,12.468565,1.752829,6.944004,14.837732,6.270211
10,24.0,906488.0,2.115162e+05,162732.247375,3.742484e+05,3.168027e+06,9.599639e+05,5.851066e+05,1.545070e+06,6.082129e+05,...,6.531474,13.816239,7.363346,1.232554,4.196380,11.842153,1.132825,7.267249,14.556853,5.646018
11,25.0,1090463.0,3.125145e+05,181526.355881,4.940409e+05,3.766528e+06,1.351093e+06,6.306814e+05,1.981774e+06,7.412920e+05,...,9.317834,11.963212,9.227425,1.600302,2.837676,11.190722,1.256162,6.231260,14.667485,5.842327
12,26.0,2574137.0,6.350301e+05,423679.264211,1.058709e+06,8.796448e+06,2.841700e+06,1.484858e+06,4.326558e+06,1.758744e+06,...,9.113343,11.555701,8.330830,1.550337,3.914139,11.554547,1.237608,6.922713,14.632194,5.860112
13,27.0,851101.0,2.848203e+05,169966.657502,4.547869e+05,3.120494e+06,1.339166e+06,5.887129e+05,1.927879e+06,7.050129e+05,...,8.850141,12.177365,6.951522,1.658246,3.543013,10.572589,1.749019,7.208879,14.573548,6.236846
14,28.0,595769.0,1.561397e+05,98570.280423,2.547100e+05,2.068017e+06,7.016725e+05,3.435836e+05,1.045256e+06,4.311663e+05,...,7.179210,12.577103,7.473057,1.567862,3.457997,12.841232,1.514385,6.408914,14.533528,5.746556
15,29.0,4126224.0,1.127378e+06,695729.187273,1.823107e+06,1.401691e+07,4.984009e+06,2.392973e+06,7.376982e+06,2.796291e+06,...,8.034479,10.909726,9.450759,1.755627,3.564898,12.389731,1.876311,5.624523,14.652896,5.996994
16,31.0,6111179.0,7.986691e+05,566099.865063,1.364769e+06,1.959733e+07,3.289483e+06,2.120316e+06,5.409800e+06,3.372977e+06,...,10.871367,12.704377,10.816944,1.722341,2.718940,12.920680,0.776309,4.630191,14.480533,3.243764
17,32.0,1113408.0,1.611276e+05,110570.222231,2.716978e+05,3.514952e+06,6.441229e+05,4.035885e+05,1.047711e+06,6.287633e+05,...,11.105058,13.709133,9.733768,1.913131,2.681253,14.146255,0.921508,4.887069,13.931062,2.621679
18,33.0,5299014.0,4.006347e+05,463806.236347,8.644410e+05,1.598993e+07,1.761830e+06,1.697668e+06,3.459498e+06,2.606836e+06,...,9.433387,11.610753,3.759746,1.169665,5.820458,13.367044,0.488988,9.887794,12.795481,3.534768
19,35.0,13053253.0,5.667999e+05,793507.392488,1.360307e+06,4.126220e+07,2.600271e+06,3.322579e+06,5.922850e+06,6.871894e+06,...,7.743551,11.694840,4.271592,1.828470,5.681349,13.523605,2.193088,9.810000,12.904182,3.143199
20,41.0,3340516.0,4.863882e+05,386097.394922,8.724856e+05,1.044453e+07,1.879602e+06,1.295670e+06,3.175272e+06,1.838515e+06,...,8.347325,14.095529,7.799962,2.142325,2.196622,12.223162,10.411707,4.577639,12.577430,2.116517
21,42.0,2015139.0,2.621774e+05,241381.046642,5.035585e+05,6.248436e+06,1.005939e+06,8.098282e+05,1.815767e+06,1.046884e+06,...,10.367715,14.913126,6.751756,2.557611,1.845556,12.024656,11.296164,3.709422,10.870022,1.498720
22,43.0,3653000.0,4.560635e+05,410678.898059,8.667424e+05,1.069393e+07,1.720336e+06,1.318657e+06,3.038993e+06,1.713767e+06,...,8.347831,14.123813,7.036864,2.177018,2.226004,12.749727,9.579048,4.544256,12.236574,2.300668
23,50.0,775003.0,1.489275e+05,127491.583659,2.764190e+05,2.449024e+06,6.093749e+05,4.204810e+05,1.029856e+06,4.773497e+05,...,7.878668,14.916112,7.750291,1.559403,2.949020,12.401671,5.160156,6.447409,13.867463,2.611866
24,51.0,932110.0,2.325066e+05,169170.455536,4.016771e+05,3.035122e+06,9.202978e+05,5.623353e+05,1.482633e+06,6.076867e+05,...,9.772571,14.520534,7.942412,1.555509,2.609378,12.468308,7.494045,5.422183,13.412153,2.675585
25,52.0,1909041.0,3.030315e+05,309707.973045,6.127395e+05,6.003788e+06,1.211356e+06,1.040788e+06,2.252144e+06,1.120130e+06,...,10.509170,15.053688,6.578047,1.879485,3.554105,14.375676,0.880532,5.762730,14.621089,2.376843
26,53.0,785733.0,3.728463e+04,48528.548064,8.581318e+04,2.570160e+06,1.811276e+05,2.041481e+05,3.852757e+05,4.790265e+05,...,5.644956,11.409314,4.072215,1.854607,6.208413,14.345270,2.673938,10.153974,13.106050,3.026328

### Por municipio

In [6]:

# municipios
municipios = pd.read_excel('Dados/MunicipioBrasil_20230102.xlsx')
display(municipios)

,cod_mun,nom_mun,cod_regiao,cod_uf,qtd_dom,qtd_dom_pobres,qtd_dom_vulneraveis,qtd_dom_pob_vul,qtd_pes,qtd_pes_pobres,...,contr_T2,contr_T3,contr_P1,contr_P2,contr_P3,contr_P4,num_idhm,num_ivs,num_ibeu,num_renda
0,1100015,Alta Floresta D'Oeste,1,11,7443.0,4815.110866,1378.041441,6193.152307,24392.0,17426.222018,...,1.458822,10.331535,12.250263,3.101195,13.260453,3.487523,0.641,0.376,0.625,548.809498
1,1100023,Ariquemes,1,11,27654.0,11601.470928,6327.880993,17929.351921,90353.0,44172.856817,...,1.979498,13.575718,10.907053,4.653805,12.506057,2.015588,0.702,0.268,0.709,762.672776
2,1100031,Cabixi,1,11,1979.0,1280.951291,468.406271,1749.357562,6313.0,4459.568118,...,0.796450,11.166553,11.696466,2.517816,14.098967,2.134615,0.650,0.300,0.665,523.394761
3,1100049,Cacoal,1,11,24413.0,6993.735293,3929.625264,10923.360558,78574.0,26757.319951,...,2.212722,11.999772,10.875981,3.901138,11.589410,3.029373,0.718,0.255,0.776,825.929402
4,1100056,Cerejeiras,1,11,5399.0,2982.974817,1054.726046,4037.700863,17029.0,10345.154932,...,2.101833,12.350372,13.383966,2.437176,13.601732,2.080656,0.692,0.280,0.674,629.383679
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5560,5222005,Vianópolis,5,52,4038.0,1008.553793,878.638149,1887.191943,12548.0,3676.940891,...,1.807658,16.679257,0.000000,3.072101,14.228158,0.731989,0.712,0.271,0.755,704.645597
5561,5222054,Vicentinópolis,5,52,2402.0,421.744543,654.041871,1075.786414,7371.0,1638.318253,...,3.509285,13.178598,1.493790,4.761815,15.466712,2.140257,0.684,0.415,0.724,673.336419
5562,5222203,Vila Boa,5,52,1418.0,413.162758,312.905870,726.068628,4735.0,1827.162128,...,3.305211,10.576442,1.248352,8.086899,15.519669,3.726185,0.647,0.384,0.740,492.615590
5563,5222302,Vila Propício,5,52,1609.0,730.010304,314.075911,1044.086215,5145.0,2547.516732,...,1.157062,13.344467,0.692964,3.442321,14.307006,2.128996,0.634,0.281,0.734,434.205380
5564,5300108,Brasília,5,53,785733.0,37284.627483,48528.548064,85813.175548,2570160.0,181127.614615,...,6.208128,14.344612,2.673815,10.153509,13.105449,3.026189,0.824,0.294,0.813,2096.594335

In [7]:
# Pegando apenas os cod_mun, nome_mun,cod_uf e cod_regiao
municipios_separacao = municipios[['cod_mun','nom_mun','cod_uf','cod_regiao']]
display(municipios_separacao)

      cod_mun                nom_mun  cod_uf  cod_regiao
0     1100015  Alta Floresta D'Oeste      11           1
1     1100023              Ariquemes      11           1
2     1100031                 Cabixi      11           1
3     1100049                 Cacoal      11           1
4     1100056             Cerejeiras      11           1
...       ...                    ...     ...         ...
5560  5222005             Vianópolis      52           5
5561  5222054         Vicentinópolis      52           5
5562  5222203               Vila Boa      52           5
5563  5222302          Vila Propício      52           5
5564  5300108               Brasília      53           5

[5565 rows x 4 columns]

In [8]:
# tabela com nomes dos estados por codigo
estados = pd.read_csv('Dados/estados_com_regiao.csv')
# mudando o nome da coluna codigo_uf para cod_uf
estados = estados.rename(columns={'codigo_uf':'cod_uf'})
# junção das tabelas municipios_separacao e estados
municipios_separacao = municipios_separacao.merge(estados, on='cod_uf')
display(municipios_separacao)

,cod_mun,nom_mun,cod_uf,cod_regiao,uf,nome,latitude,longitude,regiao
0,1100015,Alta Floresta D'Oeste,11,1,RO,Rondônia,-10.83,-63.34,Norte
1,1100023,Ariquemes,11,1,RO,Rondônia,-10.83,-63.34,Norte
2,1100031,Cabixi,11,1,RO,Rondônia,-10.83,-63.34,Norte
3,1100049,Cacoal,11,1,RO,Rondônia,-10.83,-63.34,Norte
4,1100056,Cerejeiras,11,1,RO,Rondônia,-10.83,-63.34,Norte
...,...,...,...,...,...,...,...,...,...
5560,5222005,Vianópolis,52,5,GO,Goiás,-15.98,-49.86,Centro-Oeste
5561,5222054,Vicentinópolis,52,5,GO,Goiás,-15.98,-49.86,Centro-Oeste
5562,5222203,Vila Boa,52,5,GO,Goiás,-15.98,-49.86,Centro-Oeste
5563,5222302,Vila Propício,52,5,GO,Goiás,-15.98,-49.86,Centro-Oeste
5564,5300108,Brasília,53,5,DF,Distrito Federal,-15.83,-47.86,Centro-Oeste

In [9]:
# separando cod_regiao e nom_regiao
regiao = municipios_separacao[['cod_regiao','regiao']]
regiao = regiao.drop_duplicates()
display(regiao)

      cod_regiao        regiao
0              1         Norte
449            2      Nordeste
2243           3       Sudeste
3911           4           Sul
5099           5  Centro-Oeste

#### Municipio e raça

In [10]:
# municipios por raca
municipios_raca = pd.read_excel('Dados/MUNIC_IPMporRaca_20230403.xlsx')
display(municipios_raca)

,cod_mun,raca,qtd_pessoas,qtd_pes_pobres,qtd_pes_vulneraveis,qtd_pes_pob_vul,qtd_0a11,qtd_0a11_pobres,qtd_0a11_vulneraveis,qtd_0a11_pob_vul,...,contr_S2,contr_S3,contr_S4,contr_T1,contr_T2,contr_T3,contr_P1,contr_P2,contr_P3,contr_P4
0,1100015,1,1.058332e+04,7179.226549,1992.031046,9171.257595,2089.762631,1410.233307,471.061836,1881.295142,...,12.762635,13.858319,8.597698,1.144931,1.539685,10.312575,12.087016,2.793707,12.398213,3.542948
1,1100015,2,1.094002e+03,728.312925,179.740507,908.053431,144.272802,123.646674,10.421011,134.067685,...,12.947788,13.623035,6.918102,0.978327,1.533518,9.469442,12.145569,6.469673,12.160457,2.474366
2,1100015,3,9.570439e+01,83.408552,0.000000,83.408552,0.000000,0.000000,0.000000,0.000000,...,12.885652,14.817844,10.044992,0,0,11.518,12.748534,6.175887,14.817844,0
3,1100015,4,1.212225e+04,8958.390641,1716.999407,10675.390048,2567.713721,2036.730931,304.591940,2341.322871,...,12.224243,13.412923,7.570065,1.179069,1.672537,10.139405,11.58104,4.775916,13.261225,3.619611
4,1100015,5,4.967202e+02,476.883350,19.836875,496.720225,142.410552,132.492114,9.918438,142.410552,...,10.780475,11.987448,9.833673,0,0.4005,4.673202,11.336937,9.354406,12.245565,3.201294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25441,5300108,2,1.941626e+05,19066.992026,19400.368168,38467.360194,22992.340321,3725.962154,2915.027577,6640.989731,...,4.817986,11.160995,3.199539,2.678468,7.034963,14.25135,2.633075,11.688994,12.860089,3.037806
25442,5300108,3,4.267936e+04,2142.805398,3239.454558,5382.259956,6449.173551,428.333453,645.268614,1073.602067,...,3.553672,7.366798,1.87722,4.296499,9.182302,15.502172,2.450046,11.038401,11.8873,2.068668
25443,5300108,4,1.250315e+06,114139.044161,120619.822639,234758.866800,244698.119879,31872.659458,31372.065655,63244.725113,...,4.602314,10.241986,3.205398,1.747004,6.455919,13.876508,2.556775,11.647096,12.626451,3.245807
25444,5300108,5,7.070282e+03,353.073977,759.558019,1112.631996,912.114905,46.398240,139.962241,186.360481,...,2.563905,8.017326,0,3.872857,1.315432,10.831615,4.445959,12.722702,12.281163,5.264084
25445,5300108,9,8.536041e+02,0.000000,194.986348,194.986348,144.606198,0.000000,84.431984,84.431984,...,,,,,,,,,,

#### Municipio e sexo

In [11]:
municipios_sexo = pd.read_excel('Dados/MUNIC_IPMporSexo_20230403.xlsx')
display(municipios_sexo)

,cod_mun,sexo,qtd_pessoas,qtd_pes_pobres,qtd_pes_vulneraveis,qtd_pes_pob_vul,qtd_0a11,qtd_0a11_pobres,qtd_0a11_vulneraveis,qtd_0a11_pob_vul,...,contr_S2,contr_S3,contr_S4,contr_T1,contr_T2,contr_T3,contr_P1,contr_P2,contr_P3,contr_P4
0,1100015,1,12656.0,9234.796745,1827.226063,11062.022808,2433.533535,1860.242443,399.729591,2259.972034,...,12.186224,13.350275,8.338274,1.146971,1.603338,9.740038,11.719946,4.267716,12.640239,3.516577
1,1100015,2,11736.0,8191.425273,2081.381772,10272.807045,2510.626171,1842.860584,396.263633,2239.124216,...,12.715127,13.813207,7.707203,1.075942,1.519637,10.334652,11.911296,4.095393,13.067676,3.504908
2,1100023,1,45543.0,22768.166964,9587.697225,32355.864189,9692.395538,5233.270492,1990.912458,7224.182950,...,12.375029,14.202430,4.376765,1.689845,1.934628,13.123479,10.218211,6.094876,11.852498,1.878370
3,1100023,2,44810.0,21404.689853,9840.558146,31245.247999,9377.495945,5130.635087,1862.892035,6993.527122,...,12.465686,14.414611,3.731456,1.467515,2.169754,13.025817,10.492471,6.341750,11.964273,2.197333
4,1100031,1,3266.0,2338.226108,621.726135,2959.952243,652.838209,485.784632,124.711486,610.496118,...,12.545406,13.882891,9.308115,1.433752,0.848650,11.112694,11.359339,3.541772,13.488408,2.559800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11125,5222203,2,2147.0,830.472469,440.849704,1271.322172,534.907686,248.126723,79.667910,327.794634,...,6.351118,14.226429,5.913474,1.168739,3.662520,9.977346,0.700166,10.523975,14.476074,4.493391
11126,5222302,1,2689.0,1340.085346,558.063419,1898.148766,519.096418,237.832137,85.936163,323.768301,...,13.374392,15.129351,11.062249,1.250923,1.236520,12.916189,0.494045,5.155364,13.675320,2.503695
11127,5222302,2,2456.0,1207.431386,480.863554,1688.294940,515.594771,231.812749,121.372549,353.185298,...,12.867149,14.992793,10.529991,1.492682,1.116840,12.006275,0.839633,5.983545,13.273419,3.134334
11128,5300108,1,1228880.0,91001.245116,100726.845227,191728.090343,243600.035685,24274.505358,26432.906133,50707.411491,...,4.956656,10.621847,3.512045,2.056229,6.065388,14.297255,2.482691,11.305728,12.429954,2.916014
11129,5300108,2,1341280.0,90126.369498,103421.254122,193547.623621,235426.442882,24300.957062,25873.912378,50174.869440,...,4.561536,10.104458,3.022845,1.939974,6.949604,14.150989,2.411945,11.670786,12.530556,3.236501

#### Municipio sexo e raca

#### Brasil por sexo

In [13]:
brasil_sex = pd.read_csv('Dados/sexAmdRace/UF_AgregadoporSexo_20230419.csv')
display(brasil_sex)

,local,sexo,qtd_pessoas,qtd_pes_pobres,qtd_pes_vulneraveis,qtd_pes_pob_vul,qtd_0a11,qtd_0a11_pobres,qtd_0a11_vulneraveis,qtd_0a11_pob_vul,...,contr_S2,contr_S3,contr_S4,contr_T1,contr_T2,contr_T3,contr_P1,contr_P2,contr_P3,contr_P4
0,0,1,93406989,9999899,23093210,1269809,12514237,112224,35607447,2392048,...,3280513633,12773872,8647755,18524330,2668734,11752194,7791364,2418871,327152,3878311
1,0,2,97348809,18,21825077,9394755,12698389,1960775,34523467,1355529,...,6792634223,11588120,8374534,17486532,1249312,10525273,5711,2118075,6546524,3956456
2,1,1,8004915,77,4425006,22222471,1288499,91993615,5713506,14216087,...,1729275059,2923814,82240069,3951560,4121093,2195883,90995403,453166,575458405,656057
3,1,2,7859539,51,4110346,78045351,1306158,70984524,5416505,49029875,...,8909340759,2637172,46774131,3685193,43665691,1894530,1136356,387277,355774142,657653
4,2,1,25909046,18,10482235,3274246,4604375,83375227,15086611,1611769,...,4661044815,5432900,64729257,7898541,82956538,6169092,77823427,1055107,97355902,1745811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,51,2,1485586,4,432232,698974974,272495,837102444,704728,536077418,...,7293240379,244933,513997061,401207,906331524,194206,570776857,41231,3558659565,63082
62,52,1,2981626,99999988,633284,63392365,528392,452934128,1161676,51632649,...,88254118125,377704,107702014,592563,921379507,221332,366368767,69632,1918242635,114139
63,52,2,3022161,7,578071,680093073,512395,939888113,1090467,61998119,...,74863255597,330479,597462841,540995,918079009,183410,23155973,60531,4825847702,113563
64,53,1,1228879,99999995,91001,2451161455,100726,845226798,191728,90342944,...,6223005009,29441,6622954536,63091,8980146971,20860,9301017299,9163,8937519105,27031
65,53,2,1341279,99999994,90126,3694984779,103421,254122381,193547,623620859,...,355585265435,26662,6675102795,59061,6474759873,17668,8567467498,8507,92069964567,30478

#### Brasil por sexo e raca

In [14]:
brasil_sexRace = pd.read_csv('Dados/sexAmdRace/UF_AgregadoporSexoRaca_20230419.csv')
display(brasil_sexRace)

,local,sxraca,qtd_pessoas,qtd_pes_pobres,qtd_pes_vulneraveis,qtd_pes_pob_vul,qtd_0a11,qtd_0a11_pobres,qtd_0a11_vulneraveis,qtd_0a11_pob_vul,...,contr_S2,contr_S3,contr_S4,contr_T1,contr_T2,contr_T3,contr_P1,contr_P2,contr_P3,contr_P4
0,0,1,43426847,18497,6898650,21945199,4683673,41910151,11582323,6385535,...,4924273438,3991782,6168183,5785630,7246784,3375820,62339224,762553,62226391,1080721
1,0,2,47194434,1101481,6657896,95450001,4839442,90250483,11497339,8570048,...,1579314095,3702091,73458967,5553934,56214876,3099248,73184413,688681,87895817,1138410
2,0,3,48588682,8930449,15709513,9708784,7671162,55391577,23380676,5247942,...,5408002216,8468646,34624631,12397837,77174,8035166,19558433,1586933,96742253,2743682
3,0,4,48582930,6660391,14673913,7407237,7672518,10835445,22346431,8490782,...,823181755,7583126,46161636,11581732,1160769,7099852,17110506,1362992,55070144,2754379
4,1,1,1796831,59777893,811189,876613207,294104,589005912,1105294,46561912,...,55766060355,541713,528234313,742550,535020317,362324,623329704,81103,5251351236,128116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,52,4,1682397,50282502,384909,280509927,324083,616664576,708992,897174503,...,626781810823,212249,318929573,358795,516217494,114532,137457081,40713,3938474428,77074
128,53,1,499875,554366413,22258,6761480588,28041,4222874936,50300,984355524,...,771224485369,8138,3843949534,15610,789759609,5622,52374703086,2277,29803292958,6341
129,53,2,575203,63987766,23167,229039344,31892,4873302976,55059,510234232,...,6873963344862,7138,92834172085,15154,3623435052,4796,56541504661,2600,729033095,7534
130,53,3,707382,448512456,67806,9618991044,70682,3300219418,138489,291921046,...,851076015531,21108,9661400341,47037,5079721572,15096,242468741,6637,71542963391,20355
131,53,4,737095,111245702,65399,74288217,69337,8607847647,134736,935072982,...,668188930949,19153,286514924,43112,7547561028,12749,2938685344,5629,58483755416,22280

## 2.Visualizar e tratar

#### Dando nome aos bois (Descobrindo qais regiões pertencem a codigo x)
1. Para isso foi baixada uma base de dados (https://github.com/kelvins/Municipios-Brasileiros/blob/main/csv/estados.csv)
2. Dados a partir da agregação por municipios
3. A analise vai ser feita a partir de municipios

Base de dados do github

In [21]:
estados = pd.read_csv('Dados/estados_com_regiao.csv')
display(estados.head(5))

   codigo_uf  uf      nome  latitude  longitude regiao
0         11  RO  Rondônia    -10.83     -63.34  Norte
1         12  AC      Acre     -8.77     -70.55  Norte
2         13  AM  Amazonas     -3.47     -65.10  Norte
3         14  RR   Roraima      1.99     -61.33  Norte
4         15  PA      Pará     -3.79     -52.48  Norte

In [15]:
# Pegando apenas os cod_mun, nome_mun,cod_uf e cod_regiao
municipios_separacao = municipios[['cod_mun','nom_mun','cod_uf','cod_regiao']]
# Pegando apenas os cod_mun, nome_mun,cod_uf e cod_regiao
municipios_separacao = municipios[['cod_mun','nom_mun','cod_uf','cod_regiao']]
# tabela com nomes dos estados por codigo
estados = pd.read_csv('Dados/estados_com_regiao.csv')
# mudando o nome da coluna codigo_uf para cod_uf
estados = estados.rename(columns={'codigo_uf':'cod_uf'})
# junção das tabelas municipios_separacao e estados
municipios_separacao = municipios_separacao.merge(estados, on='cod_uf')
# separando cod_regiao e nom_regiao
regiao = municipios_separacao[['cod_regiao','regiao']]
regiao = regiao.drop_duplicates()
display(regiao)

      cod_regiao        regiao
0              1         Norte
449            2      Nordeste
2243           3       Sudeste
3911           4           Sul
5099           5  Centro-Oeste

3. Aqui eu estou tratando a base Que agrega por municipio para colocar os dados das regioes e o nome dos estados

In [16]:
# colocando o nome da regiao na tabela municipios pelo cod_regiao
municipios_dois = municipios.merge(regiao, on='cod_regiao')
# trocando cod_regiao por reagiao
municipios_dois = municipios_dois.rename(columns={'regiao':'nome_regiao'})
# colocando uf na tabela municipios pelo cod_uf
municipios_dois = municipios_dois.merge(estados, on='cod_uf')
# tirando colunas desnecessarias da tabela municipios_dois latitute e longitude regiao
municipios_dois = municipios_dois.drop(columns=['latitude','longitude','regiao'])
# trocando coluna nome por nome_uf
municipios_dois = municipios_dois.rename(columns={'nome':'nome_uf'})
display(municipios_dois)

,cod_mun,nom_mun,cod_regiao,cod_uf,qtd_dom,qtd_dom_pobres,qtd_dom_vulneraveis,qtd_dom_pob_vul,qtd_pes,qtd_pes_pobres,...,contr_P2,contr_P3,contr_P4,num_idhm,num_ivs,num_ibeu,num_renda,nome_regiao,uf,nome_uf
0,1100015,Alta Floresta D'Oeste,1,11,7443.0,4815.110866,1378.041441,6193.152307,24392.0,17426.222018,...,3.101195,13.260453,3.487523,0.641,0.376,0.625,548.809498,Norte,RO,Rondônia
1,1100023,Ariquemes,1,11,27654.0,11601.470928,6327.880993,17929.351921,90353.0,44172.856817,...,4.653805,12.506057,2.015588,0.702,0.268,0.709,762.672776,Norte,RO,Rondônia
2,1100031,Cabixi,1,11,1979.0,1280.951291,468.406271,1749.357562,6313.0,4459.568118,...,2.517816,14.098967,2.134615,0.650,0.300,0.665,523.394761,Norte,RO,Rondônia
3,1100049,Cacoal,1,11,24413.0,6993.735293,3929.625264,10923.360558,78574.0,26757.319951,...,3.901138,11.589410,3.029373,0.718,0.255,0.776,825.929402,Norte,RO,Rondônia
4,1100056,Cerejeiras,1,11,5399.0,2982.974817,1054.726046,4037.700863,17029.0,10345.154932,...,2.437176,13.601732,2.080656,0.692,0.280,0.674,629.383679,Norte,RO,Rondônia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5560,5222005,Vianópolis,5,52,4038.0,1008.553793,878.638149,1887.191943,12548.0,3676.940891,...,3.072101,14.228158,0.731989,0.712,0.271,0.755,704.645597,Centro-Oeste,GO,Goiás
5561,5222054,Vicentinópolis,5,52,2402.0,421.744543,654.041871,1075.786414,7371.0,1638.318253,...,4.761815,15.466712,2.140257,0.684,0.415,0.724,673.336419,Centro-Oeste,GO,Goiás
5562,5222203,Vila Boa,5,52,1418.0,413.162758,312.905870,726.068628,4735.0,1827.162128,...,8.086899,15.519669,3.726185,0.647,0.384,0.740,492.615590,Centro-Oeste,GO,Goiás
5563,5222302,Vila Propício,5,52,1609.0,730.010304,314.075911,1044.086215,5145.0,2547.516732,...,3.442321,14.307006,2.128996,0.634,0.281,0.734,434.205380,Centro-Oeste,GO,Goiás
5564,5300108,Brasília,5,53,785733.0,37284.627483,48528.548064,85813.175548,2570160.0,181127.614615,...,10.153509,13.105449,3.026189,0.824,0.294,0.813,2096.594335,Centro-Oeste,DF,Distrito Federal

4. Deletando coulnas inuteis

Vou utilizar os dados agrupados pobres e vulneraveis juntos as que tem a tah _pob_vul

In [17]:
municipios_dois.columns

Index(['cod_mun', 'nom_mun', 'cod_regiao', 'cod_uf', 'qtd_dom',
       'qtd_dom_pobres', 'qtd_dom_vulneraveis', 'qtd_dom_pob_vul', 'qtd_pes',
       'qtd_pes_pobres', 'qtd_pes_vulneraveis', 'qtd_pes_pob_vul', 'qtd_0a11',
       'qtd_0a11_pobres', 'qtd_0a11_vulneraveis', 'qtd_0a11_pob_vul',
       'incidencia', 'intensidade', 'IPM', 'IPM_quintis', 'IPM_quintis_regiao',
       'IPM_quintis_uf', 'qtd_dom_E1', 'qtd_dom_E2', 'qtd_dom_E3',
       'qtd_dom_S1', 'qtd_dom_S2', 'qtd_dom_S3', 'qtd_dom_S4', 'qtd_dom_T1',
       'qtd_dom_T2', 'qtd_dom_T3', 'qtd_dom_P1', 'qtd_dom_P2', 'qtd_dom_P3',
       'qtd_dom_P4', 'contr_E1', 'contr_E2', 'contr_E3', 'contr_S1',
       'contr_S2', 'contr_S3', 'contr_S4', 'contr_T1', 'contr_T2', 'contr_T3',
       'contr_P1', 'contr_P2', 'contr_P3', 'contr_P4', 'num_idhm', 'num_ivs',
       'num_ibeu', 'num_renda', 'nome_regiao', 'uf', 'nome_uf'],
      dtype='object')

In [19]:
# deletando campos desnecessarios
municipios_tratado = municipios_dois.drop(columns=['qtd_dom_pobres', 'qtd_dom_vulneraveis','IPM_quintis', 'IPM_quintis_regiao',
       'IPM_quintis_uf', 'qtd_pes_pobres', 'qtd_pes_vulneraveis','qtd_0a11_pobres', 'qtd_0a11_vulneraveis','cod_mun', 'cod_regiao', 'cod_uf','nome_uf','num_ibeu','incidencia','contr_E1', 'contr_E2', 'contr_E3', 'contr_S1',
       'contr_S2', 'contr_S3', 'contr_S4', 'contr_T1', 'contr_T2', 'contr_T3',
       'contr_P1', 'contr_P2', 'contr_P3', 'contr_P4'],axis=1)
# dados numericos com no maximo duas casas decimais
pd.options.display.float_format = "{:.2f}".format
display(municipios_tratado)

,nom_mun,qtd_dom,qtd_dom_pob_vul,qtd_pes,qtd_pes_pob_vul,qtd_0a11,qtd_0a11_pob_vul,intensidade,IPM,qtd_dom_E1,...,qtd_dom_T3,qtd_dom_P1,qtd_dom_P2,qtd_dom_P3,qtd_dom_P4,num_idhm,num_ivs,num_renda,nome_regiao,uf
0,Alta Floresta D'Oeste,7443.00,6193.15,24392.00,21334.83,4944.16,4499.10,42.81,27.70,450.69,...,2556.68,4040.37,1022.83,4373.55,1150.25,0.64,0.38,548.81,Norte,RO
1,Ariquemes,27654.00,17929.35,90353.00,63601.11,19069.89,14217.71,42.08,17.65,1230.44,...,7955.65,8518.93,3634.84,9767.83,1574.27,0.70,0.27,762.67,Norte,RO
2,Cabixi,1979.00,1749.36,6313.00,5695.76,1257.89,1148.82,42.10,27.25,65.24,...,723.00,1009.35,217.28,1216.67,184.21,0.65,0.30,523.39,Norte,RO
3,Cacoal,24413.00,10923.36,78574.00,39662.27,15208.72,8365.19,42.11,12.06,748.06,...,4242.63,5125.02,1838.31,5461.21,1427.51,0.72,0.26,825.93,Norte,RO
4,Cerejeiras,5399.00,4037.70,17029.00,13307.70,3243.13,2579.55,41.03,22.67,177.28,...,1814.43,2620.66,477.21,2663.30,407.40,0.69,0.28,629.38,Norte,RO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5560,Vianópolis,4038.00,1887.19,12548.00,6447.50,2179.21,1153.97,39.18,9.79,95.34,...,791.19,0.00,194.22,899.53,46.28,0.71,0.27,704.65,Centro-Oeste,GO
5561,Vicentinópolis,2402.00,1075.79,7371.00,3723.83,1419.95,755.62,38.58,6.77,81.34,...,257.39,38.88,123.95,402.61,55.71,0.68,0.41,673.34,Centro-Oeste,GO
5562,Vila Boa,1418.00,726.07,4735.00,2765.02,1139.70,684.24,39.90,11.62,66.74,...,209.28,32.92,213.28,409.30,98.27,0.65,0.38,492.62,Centro-Oeste,GO
5563,Vila Propício,1609.00,1044.09,5145.00,3586.44,1034.69,676.95,38.90,17.65,39.41,...,454.92,31.49,156.40,650.05,96.73,0.63,0.28,434.21,Centro-Oeste,GO
5564,Brasília,785733.00,85813.18,2570160.00,385275.71,479026.48,100882.28,39.77,1.89,6346.99,...,25535.78,6343.91,24090.26,31094.04,7179.95,0.82,0.29,2096.59,Centro-Oeste,DF

Pegando os dados no tratamento feito pelas regiões na tabela de municipios separados por região

## 3.Analisar base de dados

Vamos tentar responder a pergunta "motivo da pobreza no brasil" primeiro vamos ver qual a região que tem o maior indice 

Usando a agregação por grande região